
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import localFont from 'next/font/local'
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const arcane = localFont({
  src: "../public/arcane.otf",
  variable: "--font-arcane",
});

export default function RootLayout({
  children,
}
) {
  return (
    <html lang="en">
      <body style={{ background: '#F3F4F6' }} className={`${inter.className} ${arcane.variable}`}>
        <div className="fixed top-0 left-0 right-0  z-10 flex w-full items-center justify-between bg-white px-8 py-2">
          <div className="font-arcane text-6xl text-amber-500 rounded-md w-90 h-16 px-6">
          <img src="/logo.jpg" alt="Logo" className="h-24 mb-8" />
          </div>
          <nav className="flex space-x-8">
            <Link className="text-black" href="/about">About</Link>
            <Link className="text-black" href="/prices">Prices</Link>
            <Link className="text-black" href="/program">Program</Link>
            <Link className="text-black" href="/dashboard">Dashboard</Link>
          </nav>
          <div className="bg-amber-500 rounded-lg w-32 h-12 flex justify-center items-center">Contact Us</div>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
