import { Inter } from "next/font/google";
import "../globals.css";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const arcane = localFont({
  src: "../../public/arcane.otf",
  variable: "--font-arcane",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${arcane.variable}`}>
        {children}
      </body>
    </html>
  );
}